# Operator overloading

In [1]:
#  +(add)

class Book:
    def __init__(self,p):
        self.p=p
    
    def __add__(self,other):
        return self.p+other.p
    
d1=Book(100)
d2=Book(200)
print(d1+d2)

300


In [3]:
#  +(add) for ore than 2 variables

class Book:
    def __init__(self,p):
        self.p=p
    
    def __add__(self,other):
        return Book(self.p+other.p)
    
d1=Book(100)
d2=Book(200)
d3=Book(300)
t=d1+d2+d3
print(t.p)

600


In [7]:
# >=

class Book:
    def __init__(self,p):
        self.p=p
    
    def __ge__(self,other):
        return self.p>=other.p
    
d1=Book(100)
d2=Book(200)
d1>=d2


False

In [9]:
# ==

class Book:
    def __init__(self,p):
        self.p=p
    
    def __eq__(self,other):
        return self.p>=other.p
    
d1=Book(100)
d2=Book(100)
d1==d2

True

# Abstraction
Data Hiding

In [4]:
from abc import ABC,abstractmethod

class Shape(ABC):
    def __init__(self,shape_name):
        self.shape_name=shape_name
    
    @abstractmethod
    def draw(self):
        pass
    
class Circle(Shape):
    def __init__(self):
        super().__init__('circle')
    def draw(self):
        print("It is Circle")
        
c=Circle()
c.draw()

# s=Shape("xyz")
# s.draw() We can't call object of Abstract clasS

It is Circle


# NUMPY
It is used for mathematical operatons on Array

In [6]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
arr=np.array(45)
print(arr)

45


In [10]:
ar1=np.array([5,6,7,8])
print(ar1)

[5 6 7 8]


In [12]:
arr2=np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [21]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[3,4]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [3 4]]]


In [20]:
print(arr.ndim)
print(ar1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [25]:
arr7=np.array([[[1,2]]])
arr7

array([[[1, 2]]])

In [26]:
print(arr7.ndim)

3


In [27]:
arr8=np.array([[[[1,2]]]])
arr8

array([[[[1, 2]]]])

In [28]:
print(arr8.ndim)

4
